# Generated by Django 3.0.7 on 2020-07-02 22:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackableitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 22, 58, 0, 393529, tzinfo=utc)),
        ),
    ]
