# Generated by Django 3.0.7 on 2020-07-03 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200703_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackableitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 9, 37, 407237, tzinfo=utc)),
        ),
    ]
